Repository sysone-pepper/salt-client, pull requests merged in 2024-11, with the labels that each got.

#27 [Salt 25] Feat: 노드 리사이징 일괄적용 기능 구현
  package-lock.json
  package.json
  src/App.jsx
  src/components/ProjectPage/NetworkMap.jsx
  src/components/ProjectPage/ToolBox.jsx
  src/components/common/Combobox.css
  src/components/common/Combobox.jsx
  src/constants/SizesOption.js
  src/contexts/NetworkContext.jsx
Labels: FEAT

#26 [SALT-24] Feat: 유저 전체 조회 및 삭제 기능
  src/api/User.js
  src/components/ProjectDashboardPage/AddUserModal.css
  src/components/ProjectDashboardPage/AddUserModal.jsx
  src/components/ProjectDashboardPage/UserContent.css
  src/components/ProjectDashboardPage/UserContent.jsx
  src/components/ProjectDashboardPage/ViewAllUsersModal.css
  src/components/ProjectDashboardPage/ViewAllUsersModal.jsx
  src/contexts/AuthContext.jsx
  src/pages/ProjectDashboard.css
  src/pages/ProjectDashboard.jsx
Labels: FEAT, STYLE

#19 [SALT-18] Fix: 링크 편집기능 활성화 시 노드 리사이징을 할 수 없도록 구현함
  src/components/ProjectPage/Buttons/AddButton.jsx
  src/components/ProjectPage/Buttons/Buttons.css
  src/components/ProjectPage/NetworkMap.jsx
  src/components/ProjectPage/ToolBox.jsx
  src/contexts/NetworkContext.jsx
  src/pages/ProjectPage.jsx
Labels: FIX

#34 [Salt-28] Feat: 네비게이션(미니맵) 및 리사이징 일괄적용 토글 기능 적용
  package-lock.json
  package.json
  src/assets/images/navigator-icon.png
  src/components/ProjectPage/Buttons/AddButton.jsx
  src/components/ProjectPage/Buttons/Buttons.css
  src/components/ProjectPage/CustomDeviceNode.css
  src/components/ProjectPage/CustomDeviceNode.jsx
  src/components/ProjectPage/CustomIconNode.css
  src/components/ProjectPage/CustomIconNode.jsx
  src/components/ProjectPage/NetworkMap.css
  src/components/ProjectPage/NetworkMap.jsx
  src/components/ProjectPage/ToolBox.css
  src/components/ProjectPage/ToolBox.jsx
  src/components/common/Combobox.css
  src/components/common/Combobox.jsx
  src/contexts/NetworkContext.jsx
Labels: FEAT

#38 [SALT-31] Feat: 공통 모달 구현, 구성도 대시보드 페이지에서 단건 구성도 연결 로직 구현
  src/App.jsx
  src/components/ProjectDashboardPage/AddProjectModal.jsx
  src/components/ProjectDashboardPage/ModalContents/AddProjectModalContent.css
  src/components/ProjectDashboardPage/ModalContents/AddProjectModalContent.jsx
  src/components/ProjectDashboardPage/ModalContents/AddUserModalContent.css
  src/components/ProjectDashboardPage/ModalContents/AddUserModalContent.jsx
  src/components/ProjectDashboardPage/ModalContents/ProjectSummaryModalContent.css
  src/components/ProjectDashboardPage/ModalContents/ProjectSummaryModalContent.jsx
  src/components/ProjectDashboardPage/ModalContents/ViewAllUsersModalContent.css
  src/components/ProjectDashboardPage/ModalContents/ViewAllUsersModalContent.jsx
  src/components/ProjectDashboardPage/ProjectContent.jsx
  src/components/ProjectDashboardPage/ProjectSummaryModal.jsx
  src/components/ProjectDashboardPage/ViewAllUsersModal.jsx
  src/components/ProjectPage/ModalContents/CreateNodeContent.css
  src/components/ProjectPage/ModalContents/CreateNodeContent.jsx
  src/components/ProjectPage/ModalContents/CreateObjectForm.css
  src/components/ProjectPage/ModalContents/CreateObjectForm.jsx
  src/components/ProjectPage/ModalContents/IconInput.css
  src/components/ProjectPage/ModalContents/IconInput.jsx
  src/components/ProjectPage/ModalContents/LoadDeviceForm.css
  src/components/ProjectPage/ModalContents/LoadDeviceForm.jsx
  src/components/ProjectPage/Modals/Modal.css
  src/components/ProjectPage/Modals/Modal.jsx
  src/components/ProjectPage/NetworkMap.css
  src/components/ProjectPage/NetworkMap.jsx
  src/components/ProjectPage/ToolBox.css
  src/components/ProjectPage/ToolBox.jsx
  src/components/common/Modal.css
  src/components/common/Modal.jsx
  src/contexts/NetworkContext.jsx
  src/layout/AnimatedBackground.jsx
  src/pages/ProjectDashboard.jsx
Labels: FEAT, FIX, REFACTOR, STYLE

#37 [SALT-35] Feat: tippy.js와 cytoscape-popper로 툴팁 기능 구현
  package-lock.json
  package.json
  src/components/ProjectPage/NetworkMap.jsx
Labels: FEAT

#42 [SALT-33] Feat: 배경 이미지 업데이트 기능 추가
  src/api/Graph.js
  src/assets/images/background-icon.png
  src/assets/images/object-delete-icon.png
  src/components/ProjectPage/BackgroundNode.jsx
  src/components/ProjectPage/Buttons/AddButton.jsx
  src/components/ProjectPage/ModalContents/CreateNodeContent.jsx
  src/components/ProjectPage/ModalContents/CreateObjectForm.jsx
  src/components/ProjectPage/NetworkMap.css
  src/components/ProjectPage/NetworkMap.jsx
  src/components/ProjectPage/ToolBox.jsx
  src/contexts/NetworkContext.jsx
Labels: FEAT, FIX, REFACTOR, STYLE

#44 [SALT-43] Fix: 컨플릭트 이슈 해결
  src/api/Graph.js
  src/components/ProjectPage/NetworkMap.jsx
Labels: FIX

#45 [SALT-36] Fix: 콤보박스 크기 및 툴박스 호버링 영역 조정, 리사이징 코드 삭제
  src/components/ProjectPage/ModalContents/CreateObjectForm.jsx
  src/components/ProjectPage/NetworkMap.jsx
  src/components/ProjectPage/ToolBox.css
  src/components/common/Combobox.css
  src/contexts/NetworkContext.jsx
Labels: FIX

#46 [SALT-41] Feat: 로그아웃 기능 구현 및 유저 목록 검색 기능, 새로고침 적용 기능 구현
  src/api/Diagram.js
  src/api/Graph.js
  src/api/Projects.js
  src/components/ProjectDashboardPage/ModalContents/ViewAllUsersModalContent.css
  src/components/ProjectDashboardPage/ModalContents/ViewAllUsersModalContent.jsx
  src/constants/index.jsx
  src/contexts/AuthContext.jsx
  src/contexts/NetworkContext.jsx
  src/contexts/index.jsx
  src/layout/Header.jsx
  src/pages/ProjectDashboard.jsx
  src/pages/index.jsx
Labels: FEAT

#51 [SALT-30] Feat: 대시보드 페이지 디자인 완성
  package-lock.json
  package.json
  src/App.jsx
  src/pages/ServerDashboard.css
  src/pages/ServerDashboard.jsx
Labels: FEAT, STYLE

#54 [SALT-53] Refactor: Reset CSS 정리
  index.html
  src/App.css
  src/components/ProjectDashboardPage/ProjectContent.css
  src/components/ProjectDashboardPage/UserContent.css
  src/components/auth/LoginForm.css
  src/layout/AnimatedBackground.css
  src/layout/Footer.css
  src/layout/FooterDark.css
  src/layout/Header.css
  src/pages/ProjectDashboard.css
  src/pages/ServerDashboard.css
  src/reset.css
Labels: REFACTOR

#56 [SALT-55] Feat: 사용자 경험 관련 개선
  src/components/auth/LoginForm.jsx
  src/components/common/CustomInput.jsx
  src/pages/LoginPage.jsx
  src/pages/ProjectDashboard.jsx
Labels: FEAT

#48 SALT-47 Fix: 툴박스의 텍스트를 클릭해도 해당 기능이 동작하도록 변경
  src/components/ProjectPage/Buttons/AddButton.jsx
  src/components/ProjectPage/Buttons/Buttons.css
  src/components/ProjectPage/NetworkMap.jsx
Labels: FIX

#71 [SALT-64] Feat: 장비 노드 글자 개선, 구성도 노드 인풋값을 통해 일괄 크기 조정 기능 추가, 배경 이미지 로드 시 화면 중앙맞춤 기능 추가
  src/App.jsx
  src/components/ProjectPage/CustomDeviceNode.css
  src/components/ProjectPage/CustomDeviceNode.jsx
  src/components/ProjectPage/DiagramField.jsx
  src/components/ProjectPage/NetworkMap.css
  src/constants/NavigatorConfig.js
  src/contexts/NetworkContext.jsx
  src/pages/ProjectPage.jsx
Labels: FEAT, FIX, REFACTOR, STYLE

#72 [SALT-66] Fix: 뒤로가기 시 메인 이동 관련 이슈 해결 및 푸터 이슈 해결
  src/App.jsx
  src/components/common/PrivateRoute.jsx
  src/contexts/AuthContext.jsx
  src/pages/ProjectDashboard.css
Labels: FIX

#62 [SALT-52]: Feat: 드래그엔 드롭 기능 구현
  package-lock.json
  package.json
  src/components/ProjectPage/DiagramField.jsx
  src/components/ProjectPage/NetworkMap.css
  src/components/ProjectPage/Sidebar/Row.jsx
  src/components/ProjectPage/Sidebar/Sidebar.css
  src/components/ProjectPage/Sidebar/Sidebar.jsx
  src/components/ProjectPage/Sidebar/Table.jsx
  src/components/ProjectPage/Sidebar/data.js
  src/pages/ProjectPage.css
  src/pages/ProjectPage.jsx
Labels: FEAT

#73 [SALT-59] Feat: 아이콘 노드가 리사이징 되도록 기능 개선, 아이콘 노드 생성 시 다양한 색상을 선택할 수 있도록 기능 개선
  src/components/ProjectPage/CustomIconNode.css
  src/components/ProjectPage/CustomIconNode.jsx
  src/components/ProjectPage/DiagramField.jsx
  src/components/ProjectPage/ModalContents/CreateObjectForm.jsx
  src/components/ProjectPage/ModalContents/IconInput.css
  src/components/ProjectPage/ModalContents/IconInput.jsx
Labels: FEAT, FIX, REFACTOR

#77 [SALT-74] Style 구성도 페이지 스타일 편집
  src/components/ProjectPage/Buttons/Buttons.css
  src/components/ProjectPage/DiagramField.jsx
  src/components/ProjectPage/NetworkMap.css
  src/components/ProjectPage/Sidebar/Row.jsx
  src/components/ProjectPage/Sidebar/Sidebar.css
  src/components/ProjectPage/Sidebar/Sidebar.jsx
  src/components/ProjectPage/Sidebar/Table.jsx
  src/components/ProjectPage/ToolBox.css
  src/contexts/NetworkContext.jsx
  src/layout/Header.css
  src/pages/ProjectPage.css
  src/pages/ProjectPage.jsx
Labels: STYLE

#83 [SALT-69] [Style]: Dashboard 페이지 차트 종류 변경
  package-lock.json
  package.json
  src/App.jsx
  src/api/Dashboard.js
  src/pages/ServerDashboard.css
  src/pages/ServerDashboard.jsx
Labels: STYLE

#85 [SALT-84] Feat: 텍스트 노드 기능 추가
  src/App.jsx
  src/api/Diagram.js
  src/components/ProjectDashboardPage/ProjectContent.jsx
  src/components/ProjectPage/CustomTextNode.css
  src/components/ProjectPage/CustomTextNode.jsx
  src/components/ProjectPage/DiagramField.jsx
  src/components/ProjectPage/ModalContents/CreateObjectForm.jsx
  src/components/ProjectPage/ModalContents/IconInput.jsx
  src/components/ProjectPage/ModalContents/LoadDeviceForm.css
  src/components/ProjectPage/ModalContents/TextInput.css
  src/components/ProjectPage/ModalContents/TextInput.jsx
Labels: FEAT, FIX, REFACTOR, STYLE

#89 [SALT-88] Fix: 87번 PR로 발생한 실장비 커스텀 노드 비활성화, 팝업 비활성화, 텍스트 노드 비활성화 문제 해결
  src/components/ProjectPage/DiagramField.jsx
Labels: FIX, REFACTOR

#91 [SALT-80] Feat: 드래그핸들 기능 구현
  src/components/ProjectPage/Sidebar/Sidebar.css
  src/components/ProjectPage/Sidebar/Sidebar.jsx
  src/components/ProjectPage/Sidebar/Table.jsx
Labels: FEAT

#93 [SALT-82] Feat: Light/Dark모드 적용
  src/App.css
  src/App.jsx
  src/assets/images/moon.png
  src/assets/images/salt-Logo-color.png
  src/assets/images/sun.png
  src/assets/images/white_background.jpg
  src/assets/images/white_background_2.jpg
  src/assets/images/white_background_3.jpg
  src/assets/images/white_background_4.jpg
  src/components/ProjectDashboardPage/ModalContents/AddProjectModalContent.css
  src/components/ProjectDashboardPage/ModalContents/AddUserModalContent.css
  src/components/ProjectDashboardPage/ModalContents/ProjectSummaryModalContent.css
  src/components/ProjectDashboardPage/ModalContents/ViewAllUsersModalContent.css
  src/components/ProjectDashboardPage/ProjectContent.css
  src/components/ProjectDashboardPage/UserContent.css
  src/components/auth/LoginForm.css
  src/contexts/ThemeContext.jsx
  src/index.css
  src/layout/AnimatedBackground.css
  src/layout/Footer.css
  src/layout/Footer.jsx
  src/layout/Header.css
  src/layout/Header.jsx
  src/main.jsx
  src/pages/ProjectDashboard.css
  src/pages/ProjectDashboard.jsx
Labels: FEAT, STYLE

#94 [SALT-90] Feat: url수정, 구성도 목록 조회 페이지 재 정의, 구성도 내 팝업 네비게이션 수정, 기타 버그 수정
  src/App.jsx
  src/api/Auth.js
  src/api/User.js
  src/api/index.js
  src/components/ProjectDashboardPage/ProjectContent.jsx
  src/components/ProjectPage/DiagramField.jsx
  src/components/ProjectPage/NetworkMap.css
  src/components/common/PrivateRoute.jsx
  src/constants/NavigatorConfig.js
  src/contexts/AuthContext.jsx
  src/pages/LoginPage.jsx
  src/pages/ProjectList.jsx
  src/pages/ProjectPage.css
  src/pages/ProjectPage.jsx
Labels: FEAT, FIX, REFACTOR, STYLE

#96 [SALT-95] Fix: 컨플릭트 이슈 해결
  src/App.jsx
Labels: FIX

#102 [SALT-61] Feat: 장비 구성도 내 네비게이션, 사이드 바 토글 버튼 추가
  src/assets/images/open-navigator-icon.png
  src/assets/images/sidebar-toggle-icon.png
  src/components/ProjectPage/DiagramField.jsx
  src/components/ProjectPage/NetworkMap.css
  src/components/ProjectPage/Sidebar/Row.jsx
  src/components/ProjectPage/Sidebar/Sidebar.css
  src/components/ProjectPage/Sidebar/Sidebar.jsx
  src/components/ProjectPage/Toolbar.jsx
Labels: FEAT, REFACTOR

#106 [SALT-99] Style: 차트 디자인 변경
  src/pages/ServerDashboard.css
  src/pages/ServerDashboard.jsx
Labels: STYLE

#108 [SALT-107] Feat: NIC 관련 차트 구현 및 스타일 조정
  src/components/ProjectDashboardPage/ModalContents/AddProjectModalContent.css
  src/components/ProjectDashboardPage/ModalContents/AddUserModalContent.css
  src/components/ProjectDashboardPage/ProjectContent.css
  src/components/common/Modal.css
  src/index.css
  src/pages/ServerDashboard.css
  src/pages/ServerDashboard.jsx
Labels: FEAT, STYLE

#109 [SALT-105] Feat: 사이드 바 내부에 구성도의 실장비 데이터 정보를 반영하는 기능 구현
  src/components/ProjectPage/CustomDeviceNode.jsx
  src/components/ProjectPage/DiagramField.jsx
  src/components/ProjectPage/Sidebar/Row.jsx
  src/components/ProjectPage/Sidebar/Sidebar.jsx
  src/components/ProjectPage/Sidebar/Table.jsx
  src/pages/ProjectPage.css
Labels: FEAT, FIX, REFACTOR

#111 [SALT-110] Feat: 사이드바 내 스파크라인 구현
  src/components/ProjectPage/Sidebar/Row.jsx
  src/components/ProjectPage/Sidebar/Sidebar.jsx
  src/components/ProjectPage/Sidebar/SparkLine.css
  src/components/ProjectPage/Sidebar/SparkLine.jsx
  src/hooks/useTimeout.jsx
Labels: FEAT, REFACTOR

#114 [SALT-113] Feat: 조회 기능/ 편집 기능 분리, 배경이미지, 네비게이션 등에서 발생하는 오류 부분 해결
  src/App.jsx
  src/components/ProjectPage/DiagramField.jsx
  src/components/ProjectPage/NetworkMap.css
  src/components/ProjectPage/Toolbar.css
  src/components/ProjectPage/Toolbar.jsx
  src/constants/NavigatorConfig.js
  src/contexts/AuthContext.jsx
  src/contexts/NetworkContext.jsx
  src/index.css
  src/pages/ProjectPage.css
  src/pages/ProjectPage.jsx
Labels: FEAT, FIX, REFACTOR

#119 [SALT-115] Feat: 구성도 모달창 그리드화 및 모달 스타일 수정
  package-lock.json
  package.json
  src/components/ProjectPage/CustomIconNode.jsx
  src/components/ProjectPage/ModalContents/CreateNodeContent.css
  src/components/ProjectPage/ModalContents/CreateNodeContent.jsx
  src/components/ProjectPage/ModalContents/CreateObjectForm.css
  src/components/ProjectPage/ModalContents/CreateObjectForm.jsx
  src/components/ProjectPage/ModalContents/IconInput.css
  src/components/ProjectPage/ModalContents/IconInput.jsx
  src/components/ProjectPage/ModalContents/LoadDeviceForm.css
  src/components/ProjectPage/ModalContents/LoadDeviceForm.jsx
  src/components/ProjectPage/ModalContents/TextInput.css
  src/components/ProjectPage/ModalContents/TextInput.jsx
Labels: FEAT, STYLE

#116 [SALT-112] Feat: 서버 대시보드 모달화
  src/components/ProjectPage/DiagramField.jsx
  src/components/common/Modal.css
  src/components/common/Modal.jsx
  src/pages/ServerDashboard.css
  src/pages/ServerDashboard.jsx
Labels: FEAT, STYLE

#122 [SALT-117] Feat: 썸네일 등록 기능 구현
  src/api/Diagram.js
  src/assets/images/delete.png
  src/components/ProjectDashboardPage/ProjectContent.css
  src/components/ProjectDashboardPage/ProjectContent.jsx
  src/components/ProjectPage/Toolbar.jsx
Labels: FEAT

#123 [SALT-118] Feat: 구성도 조회 페이지 사이드바 옵셔닝 구현, 구성도 조회페이지 알람 기능 기본 세팅
  src/components/ProjectPage/DiagramField.jsx
  src/components/ProjectPage/ModalContents/CreateObjectForm.jsx
  src/components/ProjectPage/ModalContents/MonitoringStatusContent.jsx
  src/components/ProjectPage/ModalContents/TopUsageOptioningContent.jsx
  src/components/ProjectPage/RotatingText.css
  src/components/ProjectPage/RotatingText.jsx
  src/components/ProjectPage/Sidebar/Row.jsx
  src/components/ProjectPage/Sidebar/Sidebar.jsx
  src/components/ProjectPage/Sidebar/Table.jsx
  src/components/ProjectPage/Toolbar.jsx
  src/constants/MonitoringOptions.js
  src/contexts/NetworkContext.jsx
Labels: FEAT, FIX, REFACTOR

#130 [SALT-129] Feat: 대시보드 차트 max value값으로 y축 설정
  src/pages/ServerDashboard.css
  src/pages/ServerDashboard.jsx
Labels: FEAT

#125 [SALT-124] Feat: 구성도 사이드바 내 옵셔닝 그리드화 및 정렬설정 스타일링
  src/components/ProjectPage/ModalContents/ChooseDeviceContent.jsx
  src/components/ProjectPage/ModalContents/CreateObjectForm.css
  src/components/ProjectPage/ModalContents/MonitoringStatusContent.jsx
  src/components/ProjectPage/ModalContents/TopUsageOptioningContent.jsx
Labels: FEAT, STYLE

#134 [SALT-133] Fix: 구성도 내 사이드바 테이블 데이터 정렬 및 장비 불러오기 탭에서 장비 타입과 장비 타입이름 매핑
  src/components/ProjectPage/ModalContents/LoadDeviceForm.jsx
  src/components/ProjectPage/Sidebar/Sidebar.css
Labels: FIX, STYLE

#132 [SALT-128] Style: 구성도 및 사이드바 화이트모드 / 다크모드 구현
  src/components/ProjectPage/Buttons/Buttons.css
  src/components/ProjectPage/DiagramField.jsx
  src/components/ProjectPage/ModalContents/CreateNodeContent.css
  src/components/ProjectPage/ModalContents/CreateObjectForm.css
  src/components/ProjectPage/ModalContents/LoadDeviceForm.css
  src/components/ProjectPage/ModalContents/LoadDeviceForm.jsx
  src/components/ProjectPage/ModalContents/MonitoringStatusContent.jsx
  src/components/ProjectPage/ModalContents/TextInput.css
  src/components/ProjectPage/NetworkMap.css
  src/components/ProjectPage/Sidebar/Sidebar.css
  src/components/ProjectPage/Toolbar.css
  src/index.css
  src/pages/ProjectPage.css
Labels: STYLE

#138 [SALT-137] Style: 사이드바 폰트 크기 조정, 텍스트가 넘칠 경우 스크롤링으로 변환
  src/components/ProjectPage/Sidebar/Row.jsx
  src/components/ProjectPage/Sidebar/Sidebar.css
Labels: FEAT, STYLE

#139 [SALT-131] Feat: 서버 API 변경에 의한 사이드바 업데이트 로직 최적화, 사이드 바 UX 개선
  package-lock.json
  package.json
  src/api/Auth.js
  src/api/Diagram.js
  src/api/index.js
  src/components/ProjectPage/DropDown.css
  src/components/ProjectPage/DropDown.jsx
  src/components/ProjectPage/ModalContents/MonitoringStatusContent.jsx
  src/components/ProjectPage/Sidebar/Row.jsx
  src/components/ProjectPage/Sidebar/Sidebar.jsx
  src/components/ProjectPage/Toolbar.jsx
  src/constants/MonitoringOptions.js
  src/pages/LoginPage.jsx
  vite.config.js
Labels: FEAT, FIX, REFACTOR, STYLE

#141 [SALT-140] Fix: 사이드바 내 테이블의 행 로직 수정
  src/components/ProjectPage/Sidebar/Row.jsx
Labels: FIX

#144 [SALT-135] Feat: 서버 대시보드 차트 추가구현
  .env
  src/assets/images/delete.png
  src/components/ProjectDashboardPage/ModalContents/ViewAllUsersModalContent.jsx
  src/components/ProjectDashboardPage/ProjectContent.css
  src/components/common/Modal.css
  src/pages/ServerDashboard.css
  src/pages/ServerDashboard.jsx
Labels: FEAT

#145 [SALT-142] Feat: 사이드바 호출 주기 및 위험/경고 레벨 수정 기능 추가
  .gitignore
  src/api/Diagram.js
  src/components/ProjectPage/DiagramField.jsx
  src/components/ProjectPage/DropDown.css
  src/components/ProjectPage/ModalContents/ControlWarningLevelContetnt.jsx
  src/components/ProjectPage/ModalContents/MonitoringStatusContent.jsx
  src/components/ProjectPage/Sidebar/Row.jsx
  src/components/ProjectPage/Sidebar/Sidebar.jsx
  src/components/ProjectPage/Toolbar.jsx
  src/contexts/NetworkContext.jsx
Labels: FEAT, FIX, REFACTOR

#149 [SALT-148] Fix : 유저 생성 오류 해결
  src/contexts/AuthContext.jsx
  src/pages/ProjectList.jsx
Labels: FEAT, FIX

#153 [SALT-150] Feat: 푸시 메세지 구현, 브라우저 알림 세팅
  src/components/ProjectDashboardPage/ModalContents/ProjectSummaryModalContent.css
  src/components/ProjectPage/DiagramField.jsx
  src/components/ProjectPage/RotatingText.jsx
  src/components/ProjectPage/Sidebar/Sidebar.jsx
  src/components/ProjectPage/Toolbar.css
  src/components/ProjectPage/Toolbar.jsx
  src/components/common/Modal.css
  src/contexts/NetworkContext.jsx
  src/hooks/usePushNotification.jsx
  src/index.css
  src/pages/ProjectList.jsx
Labels: FEAT, FIX, REFACTOR

#154 [SALT-147] Feat: DISK, NIC 탭 차트 구현
  src/components/ProjectDashboardPage/ModalContents/AddProjectModalContent.css
  src/components/ProjectDashboardPage/ModalContents/AddUserModalContent.css
  src/components/ProjectDashboardPage/ModalContents/ViewAllUsersModalContent.jsx
  src/components/common/Modal.css
  src/index.css
  src/pages/ProjectList.jsx
  src/pages/ServerDashboard.css
  src/pages/ServerDashboard.jsx
Labels: FEAT

#152 [SALT-151] Fix: 드래그 앤 드롭을 수행하면 오류가 발생하는 문제 수정
  src/components/ProjectPage/DropDown.jsx
  src/components/ProjectPage/ModalContents/ControlWarningLevelContetnt.jsx
  src/components/ProjectPage/NetworkMap.css
  src/components/ProjectPage/Sidebar/Sidebar.css
  src/components/ProjectPage/Sidebar/Sidebar.jsx
  src/components/ProjectPage/Toolbar.css
  src/index.css
Labels: FIX

#161 [SALT-86] Feat : 유저 권한에 따른 분기, 아이콘 변경
  src/assets/images/L2Switch-icon.png
  src/assets/images/L3Switch-icon.png
  src/assets/images/L4Switch-icon.png
  src/assets/images/L7Switch-icon.png
  src/components/ProjectDashboardPage/ProjectContent.jsx
  src/components/ProjectPage/CustomDeviceNode.jsx
  src/components/ProjectPage/DiagramField.jsx
  src/components/ProjectPage/ModalContents/CreateObjectForm.jsx
  src/pages/ProjectList.jsx
Labels: FEAT, REFACTOR

#163 [SALT-162] Feat : 모니터링 알람 관련 기능 개선, 기타 오류 수정
  src/components/ProjectPage/DiagramField.jsx
  src/components/ProjectPage/RotatingText.jsx
  src/components/ProjectPage/Sidebar/Sidebar.jsx
  src/components/ProjectPage/Toolbar.jsx
Labels: FEAT, FIX

#167 [SALT-116] Fix : CORS 이슈 픽스
  src/api/index.js
Labels: FIX
